# https://travis-ci.org/#!/HearthSim/stove
sudo: false
language: go
go:
  - 1.5
install:
  - go get github.com/HearthSim/hs-proto/go
  - go get github.com/golang/protobuf/proto
  - go get github.com/jinzhu/gorm
  - go get github.com/mattn/go-sqlite3
  - ./bootstrap.sh
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
